config/routes.rb
require 'resque/server'


CodeTriage::Application.routes.draw do
  get "users/sign_in" => redirect('/users/auth/github'), via: [:get, :post]
  get "users/sign_up" => redirect('/users/auth/github'), via: [:get, :post]

  devise_for  :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks",  registrations: "users"}

  root        to: "pages#index"

  namespace :users do
    resources :after_signup
  end

  resources   :users
  get         "/users/unsubscribe/:account_delete_token" => "users#token_delete", as: :token_delete_user
  delete      "/users/unsubscribe/:account_delete_token" => "users#token_destroy"

  resources   :issue_assignments

  get "/issue_assignments/:id/users/:user_id/click", to: "issue_assignments#click_redirect", as: :issue_click

  resources   :repo_subscriptions

  if Rails.env.development?
    mount UserMailer::Preview => 'mail_view'
  end

  mount Resque::Server.new, at: "/codetriage/resque"

  # format: false gives us rails 3.0 style routes so angular/angular.js is interpreted as
  # user_name: "angular", name: "angular.js" instead of using the "js" as a format
  scope format: false do
    resources :repos, only: %w[index new create]

    scope '*full_name' do
      constraints full_name: REPO_PATH_PATTERN do
        get   '/',            to: 'repos#show',        as: 'repo'
        patch '/',            to: 'repos#update',      as:  nil
        get   '/edit',        to: 'repos#edit',        as: 'edit_repo'
        get   '/subscribers', to: 'subscribers#show',  as: 'repo_subscribers'
      end
    end
  end
end

app/models/repo.rb
class Repo < ActiveRecord::Base
  include ResqueDef

  validate :github_url_exists, on: :create
  validates :name, uniqueness: {scope: :user_name, case_sensitive: false }
  validates :name, :user_name, presence: true

  has_many :issues
  has_many :repo_subscriptions
  has_many :users, through: :repo_subscriptions
  has_many :subscribers, through: :repo_subscriptions, source: :user

  delegate :open_issues, to: :issues

  before_validation :downcase_name, :strip_whitespaces
  before_save :set_full_name
  after_create :populate_issues!, :update_repo_info!

  def subscriber_count
    users.count
  end

  # pulls out number of issues divided by number of subscribers
  def self.order_by_need
     joins(:repo_subscriptions).order("issues_count::float/COUNT(repo_subscriptions.repo_id) DESC").group("repos.id")
  end

  # these repos have no subscribers and have no buisness being in our database
  def self.inactive
    joins("LEFT OUTER JOIN repo_subscriptions on repos.id = repo_subscriptions.repo_id").where("repo_subscriptions.repo_id is null")
  end

  def self.not_in(*ids)
    where("repos.id not in (?)", ids)
  end

  def self.rand
    order("random()")
  end

  def self.all_languages
    self.select("language").group("language").map(&:language).reject(&:blank?)
  end

  def self.repos_needing_help_for_user(user)
    if user && user.has_favorite_languages?
      where(language: user.favorite_languages)
    else
      self
    end.with_some_issues.order_by_issue_count
  end

  def force_issues_count_sync!
     self.update_attributes(issues_count: self.issues.where(state: "open").count)
  end

  def to_param
    path
  end

  def self.order_by_issue_count
    self.order("issues_count DESC")
  end

  def self.search_by(repo_name, user_name)
    where(name: repo_name.downcase.strip, user_name: user_name.downcase.strip)
  end

  def self.with_some_issues
    self.where("issues_count > 0")
  end

  def github_url_exists
    GitHubBub.get(api_issues_path, page: 1, sort: 'comments', direction: 'desc')
  rescue GitHubBub::RequestError
    errors.add(:expiration_date, "cannot reach api.github.com/#{api_issues_path} perhaps github is down, or you mistyped something?")
  end

  def github_url
    File.join('https://github.com', path)
  end

  def issues_url
    File.join(github_url, 'issues')
  end

  def path
    "#{user_name}/#{name}"
  end

  def api_issues_path
    File.join('repos', path, '/issues')
  end

  def api_issues_url
    File.join("https://api.github.com", api_issues_path)
  end

  def populate_issues!
    background_populate_issues(self.id)
  end

  def self.exists_with_name?(name)
    user_name, repo_name = name.downcase.split(?/)
    Repo.exists?(user_name: user_name, name: repo_name)
  end

  def self.order_by_subscribers
    joins("LEFT OUTER JOIN repo_subscriptions
           ON repo_subscriptions.repo_id = repos.id
           LEFT OUTER JOIN users ON users.id = repo_subscriptions.user_id").
      group("repos.id").
      order("count(users.id) DESC")
  end

  # This class is used by resque,
  # by default anything you put into the perform method
  # will be called for each object in the redis queue
  resque_def(:background_populate_issues) do |id|
    begin
      repo = Repo.find(id.to_i)
      repo.populate_multi_issues!(state: 'open')
    rescue GitHubBub::RequestError => e
      repo.update_attributes(github_error_msg: e.message)
    end
  end


  def populate_issue(options = {})
    page  = options[:page]||1
    state = options[:state]||"open"
    response = GitHubBub.get(api_issues_path, state:     state,
                                              page:      page,
                                              sort:      'comments',
                                              direction: 'desc')
    response.json_body.each do |issue_hash|
      logger.info "Issue: number: #{issue_hash['number']}, updated_at: #{issue_hash['updated_at']}"
      Issue.find_or_create_from_hash!(issue_hash, self)
    end
    response
  end


  def populate_multi_issues!(options = {})
    options[:state] ||= "open"
    options[:page]  ||= 1
    response = populate_issue(options)
    until response.last_page?
      options[:page] += 1
      response = populate_issue(options)
    end
  end

  def update_from_github
    resp = GitHubBub.get(repo_path).json_body
    self.language    = resp['language']
    self.description = resp['description']
    self.save
  end

  def repo_path
    File.join 'repos', path
  end

  def update_repo_info!
    background_update_repo_info(self.id)
  end

  resque_def(:background_update_repo_info) do |id|
    repo = Repo.find(id)
    repo.update_from_github
  end

  def self.find_by_full_name(full_name)
    Repo.includes(:issues).find_by!(full_name: full_name)
  end

  private

  def downcase_name
    self.name.downcase!
    self.user_name.downcase!
  end

  def set_full_name
    self.full_name = "#{user_name}/#{name}"
  end

  def strip_whitespaces
    self.name.strip!
    self.user_name.strip!
  end

end

app/controllers/repos_controller.rb
require File.expand_path("../../../lib/sorted_repo_collection", __FILE__)

class ReposController < RepoBasedController

  before_filter :authenticate_user!, only: [:new, :create, :edit, :update]

  def index
    @repos = Repo.order_by_subscribers.order(:name).page(params[:page]).per_page(params[:per_page] || 50)
  end

  def new
    @repo = Repo.new(user_name: params[:user_name], name: name_from_params(params))
    if user_signed_in?
      @own_repos = Rails.cache.fetch("user/repos/#{current_user.id}", expires_in: 30.minutes) do
        own_repos_response = GitHubBub.get("/user/repos", token: current_user.token, type: "owner", per_page: '100')
        SortedRepoCollection.new(own_repos_response.json_body)
      end

      @starred_repos = Rails.cache.fetch("users/starred/#{current_user.id}", expires_in: 30.minutes) do
        starred_repos_response = GitHubBub.get("/user/starred", token: current_user.token)
        SortedRepoCollection.new(starred_repos_response.json_body)
      end

      @watched_repos = Rails.cache.fetch("users/subscriptions/#{current_user.id}", expires_in: 30.minutes) do
        watched_repos_response = GitHubBub.get("/user/subscriptions", token: current_user.token)
        SortedRepoCollection.new(watched_repos_response.json_body)
      end
    end
  end

  def show
    @repo        = find_repo(params)
    @issues      = @repo.open_issues.order("created_at DESC").page(params[:page]).per_page(params[:per_page]||20)
    @repo_sub    = current_user.repo_subscriptions_for(@repo.id).first if current_user
    @subscribers = @repo.subscribers.public_profile.limit(27)
  end

  def create
    parse_params_for_repo_info
    @repo   = Repo.search_by(params[:repo][:name], params[:repo][:user_name]).first
    @repo ||= Repo.create!(repo_params)

    if @repo.save
      flash[:notice] = "Added #{@repo.to_param} for triaging"
      repo_sub = RepoSubscription.create!(repo_id: @repo.id, user_id: current_user.id)
      RepoSubscription.background_send_triage_email(repo_sub.id)

      redirect_to @repo
    else
      response = GitHubBub.get("/user/repos", type: "owner", token: current_user.token)
      @own_repos = response.json_body
      render :new
    end
  end

  def edit
    @repo = find_repo(params)
    redirect_to root_path, notice: "You cannot edit this repo" unless current_user.able_to_edit_repo?(@repo)
  end

  def update
    @repo = find_repo(params)
    if @repo.update_attributes(repo_params)
      redirect_to @repo, notice: "Repo updated"
    else
      render :edit
    end
  end

  private

    def repo_params
      params.require(:repo).permit(
        :notes,
        :name,
        :user_name,
        :issues_count,
        :language,
        :description,
        :full_name
        )
    end

    def parse_params_for_repo_info
      if params[:url]
        params[:url].match(/^https:\/\/github\.com\/([^\/]*)\/([^\/]*)\/?$/)
        params[:repo] ||= {}
        params[:repo][:user_name] = $1
        params[:repo][:name] = $2
      end
    end
end

app/views/repos/_repo.html.erb
<li>
  <span class="label label-info" data-toggle="tooltip" title="<%= pluralize(repo.issues_count, 'Issue') %>"><%= repo.issues_count %></span>
  <h4>
    <%= link_to repo.name, repo %>
    <%= " <small>(#{repo.full_name})</small> ".html_safe if repo.full_name.present? %>
  </h4>
  <p><%= raw repo.description %></p>
</li>

app/views/repos/edit.html.erb
<h2>Editing repo <%= @repo.full_name %></h2>

<%= form_for @repo do |f| %>

  <p>As a repo owner you are able to add some text to your repos page to encourage users to subscribe to your project and help out.  You may also want to add additional information on the best ways to help out and any common things that people might want to know in advance.</p>
  <p>Markdown is supported here</p>

  <p>
    <%= f.text_area :notes, class: 'span6', rows: 5 %>
  </p>

  <div class="">
    <%= f.submit "Update repo", class: 'btn btn-primary' %>
    <%= link_to "Cancel", repo_path(@repo), class: 'btn' %>
  </div>

<% end -%>

app/views/repos/index.html.erb
<h2>Subscribe To a Repo on GitHub</h2>

<%= render 'shared/repos', repos: @repos %>

<%= will_paginate @repos %>

app/views/repos/new.html.erb
<% @repo.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
<% end %>

<% if user_signed_in? %>
  <h2>Your repos</h2>
  <p>Only repos that have GitHub issues enabled are shown</p>

    <ul class="nav nav-tabs" data-tabs="tabs" id="repo-tabs">
      <li><a href="#own" data-toggle="tab">Your own repos</a></li>
      <li><a href="#starred" data-toggle="tab">Starred repos</a></li>
      <li><a href="#watched" data-toggle="tab">Watched repos</a></li>
    </ul>

    <div class="tab-content ">
      <div class="tab-pane active" id="own">
        <%= render 'shared/add_repos_list', repos: @own_repos %>
      </div>

      <div class="tab-pane active" id="starred">
        <%= render 'shared/add_repos_list', repos: @starred_repos %>
      </div>

      <div class="tab-pane active" id="watched">
        <%= render 'shared/add_repos_list', repos: @watched_repos %>
      </div>
    </div>

<% end -%>
<h3>Add another repo</h3>

<h4>by entering the user and repo name</h4>
<%= form_for @repo, html: { id: "new_repo_from_names" } do |f| %>
  https://github.com/
  <%= f.text_field :user_name, placeholder: 'user name e.g. "schneems" ', class: 'preview_user_name' %> /
  <%= f.text_field :name, placeholder: 'repo name e.g. "sextant" ', class: 'preview_repo_name' %>
  <%= f.submit value: "Add Repo", class: 'btn btn-primary', id: 'createRepo' %>
  <p id="repo_preview" class="repo_preview">
    Preview: <a href='https://github.com' target='_blank'>https://github.com/</a>
  </p>
<% end %>

<h4>or by pasting the full repo URL</h4>
<%= form_tag repos_path, {class: "new_repo", id: "new_repo_from_url"} do %>
  <%= text_field_tag :url, nil, placeholder: 'full url e.g. "https://github.com/schneems/sextant', class: 'url_field' %>
  <%= submit_tag nil, value: "Add Repo", class: 'btn btn-primary', id: 'createRepo' %>
<% end %>

app/views/repos/show.html.erb
<h1><%= @repo.name %> <small><%= @repo.language %></small></h1>
<p><%= link_to @repo.github_url, @repo.github_url %> </p>
<p>
  <%= @repo.description %>
</p>
<% unless @repo.notes.blank? %>
  <p>
    <%= raw BlueCloth.new(@repo.notes).to_html %>
  </p>
<% end -%>
<hr />


<ul class="unstyled avatars_list">
  <%= render 'subscribers/avatars', subscribers: @subscribers, show_names: false %>
  <% if (difference = @repo.subscribers.count - @subscribers.count) && difference > 0  %>
    <li class='more'><%= link_to 'more' , repo_subscribers_path(full_name: @repo.full_name) %></li>
  <% end %>
</ul>

<p>
  <%= link_to repo_subscribers_path(full_name: @repo.full_name) do %>
    <%=  @repo.subscribers.count %> Subscribers
  <% end %>
</p>

<p>
  <% if user_signed_in? && current_user.able_to_edit_repo?(@repo) %>
    <%= link_to "Edit this repo", edit_repo_path(@repo), class: 'btn btn-primary' %>
  <% end -%>

  <% if @repo_sub %>
      <%= link_to repo_subscription_path(@repo_sub), class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } do %>
        <i class="icon-remove icon-white"></i> Stop Triaging
      <% end %>
  <% end -%>
</p>

<hr />

<h2>Help Triage Issues!</h2>
<p>
	When you volunteer to triage issues, you'll receive an email each day with a link to an open issue that needs to be triaged in this project. You'll also receive instructions on how to triage issues.
</p>

<% if @repo_sub.blank? %>
  <%= button_to "I Want to Triage: #{@repo.path}", repo_subscriptions_path(repo_id: @repo.id), class: 'btn btn-primary btn-success' %>
<% else %>
  <p>
    <%= link_to issue_assignments_path(id: @repo_sub.id), class: 'btn btn-success', method: :post do %>
      <i class="icon-envelope icon-white"></i> Send new issue!
    <% end %>
  </p>
  <p>
    Currently receiving <%= @repo_sub.email_limit %> issues per day.
    <%= form_for(@repo_sub, html: {class: 'form-inline'}) do |f| %>
      <%= f.select :email_limit, (1..20) %>
      <%= f.submit "Save", class: 'btn btn-success' %>
    <% end %>
  </p>
<% end %>

<hr />
<h2><%= @issues.total_entries %> open issues in <%= @repo.path %></h2>

<div class="digg_pagination">
  <div clas="page_info">
    <%#= page_entries_info @issues %>
  </div>
  <br />
  <%= will_paginate @issues, container: false %>
</div>
<br />
  <ul>
    <% @issues.each do |issue| %>
      <li>
        <%= link_to issue.title, issue.html_url %>
      </li>
    <% end %>
  </ul
<hr />